import openai

openai.api_key = 'sk-BMXKbZ7rS9XBN9GV2I9ECla-QU4_z4dsgQeb6egTvjT3BlbkFJihF14nU3K2U7GJ4JLZZM0nm6TJv9Jym1jxjfdRSnsA'

def get_pos_tags_with_gpt(sentences):
    formatted_sentences = "\n".join(sentences)
    response = openai.ChatCompletion.create(
        model="gpt-4-turbo",  
        messages=[
            {"role": "system", "content": "You are a POS tagging assistant."},
            {"role": "user", "content": f"Please tag each word in the following sentences with its part of speech (POS) tags. Return the result in this format:\n\nsentence - [word1 word2 ... wordn]\ntags - [tag1 tag2 ... tagn]\n\nHere are the sentences:\n{formatted_sentences}"}
        ]
    )

    pos_tags = response['choices'][0]['message']['content']
    return pos_tags

if __name__ == "__main__":
    sentences = [
    "Although she was tired, she continued working late into the night.",
    "The man who sold the world is now a legend in the music industry.",
    "When the rain started, we quickly ran inside the house to avoid getting wet.",
    "Despite the warnings, they ventured into the dense forest without any equipment.",
    "The scientist, who won the Nobel Prize, delivered an inspiring speech at the conference.",
    "After eating lunch, I decided to take a quick nap before heading to the gym.",
    "If you don’t study, you might fail the exam, which could impact your future.",
    "The book that I bought yesterday was written by a famous author from France.",
    "While walking to the store, I saw a cat chasing a squirrel across the street.",
    "The movie, which was released last year, has received critical acclaim worldwide.",
    "She enjoys painting landscapes, but she finds portraits challenging to create.",
    "Whenever I visit my grandmother, she always bakes my favorite cookies.",
    "The artist, known for his abstract paintings, held an exhibition in New York.",
    "Because of the heavy traffic, we arrived at the airport just in time for our flight.",
    "The team that won the championship worked hard all season to achieve their goal.",
    "During the summer vacation, we traveled to several countries in Europe.",
    "The student who studies the hardest will likely get the highest grade in the class.",
    "As soon as the bell rang, the students rushed out of the classroom eagerly.",
    "The project, which was started two years ago, is finally nearing completion.",
    "Although it was raining, the children insisted on playing outside in the garden.",
    "The singer, whose album topped the charts, has a unique and powerful voice.",
    "The company, which was founded in 1990, has grown into a global corporation.",
    "Whenever he feels stressed, he takes a walk in the park to clear his mind.",
    "The laptop that you bought last month is already having issues with its battery.",
    "After finishing her homework, she helped her brother with his math problems.",
    "The mountain, covered in snow, looked majestic under the bright sunlight.",
    "The chef, famous for his culinary skills, opened a new restaurant downtown.",
    "If you save your money, you can afford to buy that car you've been wanting.",
    "The garden, filled with colorful flowers, was a sight to behold in the spring.",
    "The teacher, who has been teaching for 20 years, is loved by all her students.",
    "The book, which was translated into several languages, became an international bestseller.",
    "The company decided to launch a new product line to attract younger customers.",
    "Despite the challenges, she managed to complete the marathon in under four hours.",
    "The child, who was lost in the mall, was found by a security guard near the entrance.",
    "As the sun set, the sky turned a beautiful shade of pink and orange.",
    "The musician, who played the piano, captivated the audience with his performance.",
    "If you don't water the plants regularly, they will wither and die.",
    "The detective, who solved the complex case, was awarded a medal of honor.",
    "The storm, which had been forecasted for days, finally hit the coast with full force.",
    "The artist, who painted the mural, used vibrant colors to depict the scene.",
    "After the meeting, the employees discussed the new policies in the break room.",
    "The old house, which had been abandoned for years, was finally renovated.",
    "The actress, who starred in the movie, received praise for her outstanding performance.",
    "The cake, which was decorated with fresh berries, was the highlight of the party.",
    "The dog, which had been missing for days, was found safe and sound in the park.",
    "The pilot, who had extensive experience, safely landed the plane during the storm.",
    "The novel, which was written by a debut author, received mixed reviews from critics.",
    "The bridge, which connects the two cities, was closed for repairs last week.",
    "The artist, who sculpted the statue, drew inspiration from ancient mythology.",
    "After the concert, the band members signed autographs for their fans.",
    "The flowers, which bloomed in the spring, added color to the otherwise dull garden.",
    "The student, who excelled in mathematics, was awarded a scholarship to a prestigious university.",
    "Despite the cold weather, the marathon runners pushed through to the finish line.",
    "The actor, who played the villain in the movie, delivered a chilling performance.",
    "The scientist, who conducted the experiment, published her findings in a leading journal.",
    "The park, which was recently renovated, now has a new playground for children.",
    "The photographer, who captured the stunning landscape, won an award for his work.",
    "The restaurant, which was known for its delicious cuisine, was always crowded on weekends.",
    "The musician, who composed the symphony, was inspired by the beauty of nature.",
    "The castle, which stood on the hill, was a popular tourist attraction in the region.",
    "The athlete, who broke the world record, trained rigorously for years to achieve this feat.",
    "The movie, which was based on a true story, moved the audience to tears.",
    "The ship, which had been lost at sea, was finally found by a search team.",
    "The poet, who wrote the famous sonnet, was admired for his mastery of language.",
    "The village, which was nestled in the mountains, was known for its scenic beauty.",
    "The scientist, who discovered the new element, made a significant contribution to chemistry.",
    "The painting, which depicted a serene landscape, was displayed in the art gallery.",
    "The chef, who cooked the gourmet meal, was praised for his culinary expertise.",
    "The book, which was set in the Victorian era, provided a glimpse into life during that time.",
    "The pianist, who performed at the concert, captivated the audience with his skill.",
    "The city, which was founded centuries ago, has a rich history and culture.",
    "The mountain, which was covered in snow, attracted many skiers during the winter season.",
    "The scientist, who developed the vaccine, saved countless lives with her invention.",
    "The garden, which was filled with roses, was a favorite spot for visitors.",
    "The actor, who starred in the blockbuster, became an overnight sensation.",
    "The train, which was running late, finally arrived at the station after a long delay.",
    "The singer, who had a powerful voice, left the audience in awe with her performance.",
    "The river, which flowed through the valley, provided water for the nearby farms.",
    "The building, which was constructed in the 19th century, is a historical landmark.",
    "The artist, who drew the intricate design, showcased her talent at the exhibition.",
    "The forest, which was home to diverse wildlife, was a protected area.",
    "The author, who wrote the bestselling novel, was invited to speak at the literary festival.",
    "The city, which was bustling with activity, was a hub for trade and commerce.",
    "The soldier, who fought bravely in the war, was honored with a medal of valor.",
    "The lighthouse, which stood tall on the cliff, guided ships safely to shore.",
    "The chef, who specialized in French cuisine, opened a restaurant in the city center.",
    "The lake, which was surrounded by mountains, was a popular destination for tourists.",
    "The scientist, who won the prestigious award, dedicated her success to her mentors.",
    "The car, which had been parked for days, was finally moved to a different location.",
    "The garden, which was meticulously maintained, won the first prize in the flower show.",
    "The teacher, who had a passion for literature, inspired her students to love reading.",
    "The musician, who played the violin, enchanted the audience with her performance.",
    "The village, which was famous for its pottery, attracted artists from around the world.",
    "The building, which was recently renovated, now houses a modern art museum.",
    "The scientist, who led the research team, made a groundbreaking discovery.",
    "The artist, who painted the portrait, captured the subject’s essence perfectly.",
    "The island, which was located in the Pacific Ocean, was known for its beautiful beaches.",
    "The bridge, which spanned the river, connected the two parts of the city.",
    "The poet, who penned the famous verses, was regarded as a literary genius.",
    "The city, which was known for its vibrant nightlife, attracted tourists from all over the world.",
    "foxes foxes fox fox foxes."]
    
    pos_tags = get_pos_tags_with_gpt(sentences)
    print(pos_tags)
